services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=postgres
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database:
